name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  intl: ^0.19.0
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.20.0
  flutter_lints: 4.0.0
  mocktail: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/Arrow - Left 2.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts\Poppins-Bold.ttf
          weight: 700
        - asset: fonts\Poppins-Medium.ttf
          weight: 500
        - asset: fonts\Poppins-Regular.ttf
          weight: 400
        - asset: fonts\Poppins-SemiBold.ttf
          weight: 600

