name: movie_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.20.0
  flutter_lints: 4.0.0
  build_runner: 2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/icons/Arrow - Left 2.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts\Poppins-Bold.ttf
          weight: 700
        - asset: fonts\Poppins-Medium.ttf
          weight: 500
        - asset: fonts\Poppins-Regular.ttf
          weight: 400
        - asset: fonts\Poppins-SemiBold.ttf
          weight: 600

